version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    env_file:
      - ./.env.local
    volumes:
      - mongo:/data/db
    ports:
      - '600:27017'

volumes:
  mongo: